// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/DoHongKien/go-structure/internal/controller"
	"github.com/DoHongKien/go-structure/internal/repo"
	"github.com/DoHongKien/go-structure/internal/service"
)

// Injectors from customer.wire.go:

func InitCustomerRouterHandler() (*controller.CustomerController, error) {
	iCustomerRepository := repo.NewCustomerRepository()
	iCustomerService := service.NewCustomerService(iCustomerRepository)
	customerController := controller.NewCustomerController(iCustomerService)
	return customerController, nil
}

// Injectors from order.wire..go:

func InitOrderRouterHandler() (*controller.OrderController, error) {
	iOrderRepository := repo.NewOrderRepository()
	iOrderService := service.NewOrderService(iOrderRepository)
	orderController := controller.NewOrderController(iOrderService)
	return orderController, nil
}

// Injectors from order_detail.wire.go:

func InitOrderDetailRouterHandler() (*controller.OrderDetailController, error) {
	iOrderDetailRepository := repo.NewOrderDetailRepository()
	iOrderDetailService := service.NewOrderDetailService(iOrderDetailRepository)
	orderDetailController := controller.NewOrderDetailController(iOrderDetailService)
	return orderDetailController, nil
}
