// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTestGenMysqlToGo = "test_gen_mysql_to_go"

// TestGenMysqlToGo mapped from table <test_gen_mysql_to_go>
type TestGenMysqlToGo struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Uname string `gorm:"column:uname" json:"uname"`
	Upass string `gorm:"column:upass" json:"upass"`
}

// TableName TestGenMysqlToGo's table name
func (*TestGenMysqlToGo) TableName() string {
	return TableNameTestGenMysqlToGo
}
