server:
  port: 9999
  mode: dev
mysql:
  host: localhost
  port: 3306
  username: root
  password: 2003
  dbname: ecommerce
  maxIdleConns: 10
  maxOpenConns: 1000
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
jwt:
  secret_key: hNsdQK8zfPFpnSnnqTmqX5aI94c3Npd/QdkkvQhHLI+q0VOpe1AJk9NEMgC8awfy
  expire_time: 3600