package main

import (
	"github.com/DoHongKien/go-structure/internal/initialize"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/DoHongKien/go-structure/cmd/swag/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Go Structure API
// @version 1.0
// @description This is a sample server for demonstrating Swagger with Go.
// @host localhost:9999
// @BasePath /
func main() {

	r := initialize.Run()

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":9999")
}
